class BasePageLocators:
    DESCRIPTION_PAGE = ("css selector", "#ember5.ember-view")
    TELEGRAM_PAGE = ("css selector", ".text-s a:nth-child(2).inline-block")
    MORE_MENU = ("css selector", "#other-menu > input")
    DONATE_PAGE = ("xpath", "//div[@id='other-menu']//a[1]")
    CONTACTS = ("xpath", "//div[@id='other-menu']//a[3]")
    SPECIALISTS_PAGE = ("xpath", "//div[@id='other-menu']//a[5]")
    GITHUB = ("xpath", "//div[@id='other-menu']//a[2]")
    CONTRIBUTORS_PAGE = ("xpath", "//div[@id='other-menu']//a[6]")
    USED_RESOURCES_PAGE = ("xpath", "//div[@id='other-menu']//a[7]")